// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	store "github.com/cmelgarejo/go-modulith-template/modules/auth/internal/db/store"
	repository "github.com/cmelgarejo/go-modulith-template/modules/auth/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BlacklistToken mocks base method.
func (m *MockRepository) BlacklistToken(ctx context.Context, tokenHash, userID, reason string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlacklistToken", ctx, tokenHash, userID, reason, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// BlacklistToken indicates an expected call of BlacklistToken.
func (mr *MockRepositoryMockRecorder) BlacklistToken(ctx, tokenHash, userID, reason, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlacklistToken", reflect.TypeOf((*MockRepository)(nil).BlacklistToken), ctx, tokenHash, userID, reason, expiresAt)
}

// CleanupExpiredBlacklistEntries mocks base method.
func (m *MockRepository) CleanupExpiredBlacklistEntries(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredBlacklistEntries", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredBlacklistEntries indicates an expected call of CleanupExpiredBlacklistEntries.
func (mr *MockRepositoryMockRecorder) CleanupExpiredBlacklistEntries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredBlacklistEntries", reflect.TypeOf((*MockRepository)(nil).CleanupExpiredBlacklistEntries), ctx)
}

// CleanupExpiredMagicCodes mocks base method.
func (m *MockRepository) CleanupExpiredMagicCodes(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredMagicCodes", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredMagicCodes indicates an expected call of CleanupExpiredMagicCodes.
func (mr *MockRepositoryMockRecorder) CleanupExpiredMagicCodes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredMagicCodes", reflect.TypeOf((*MockRepository)(nil).CleanupExpiredMagicCodes), ctx)
}

// CleanupExpiredOAuthStates mocks base method.
func (m *MockRepository) CleanupExpiredOAuthStates(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredOAuthStates", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExpiredOAuthStates indicates an expected call of CleanupExpiredOAuthStates.
func (mr *MockRepositoryMockRecorder) CleanupExpiredOAuthStates(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredOAuthStates", reflect.TypeOf((*MockRepository)(nil).CleanupExpiredOAuthStates), ctx)
}

// CleanupExpiredSessions mocks base method.
func (m *MockRepository) CleanupExpiredSessions(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExpiredSessions", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CleanupExpiredSessions indicates an expected call of CleanupExpiredSessions.
func (mr *MockRepositoryMockRecorder) CleanupExpiredSessions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExpiredSessions", reflect.TypeOf((*MockRepository)(nil).CleanupExpiredSessions), ctx)
}

// CountExternalAccountsByUserID mocks base method.
func (m *MockRepository) CountExternalAccountsByUserID(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExternalAccountsByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExternalAccountsByUserID indicates an expected call of CountExternalAccountsByUserID.
func (mr *MockRepositoryMockRecorder) CountExternalAccountsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExternalAccountsByUserID", reflect.TypeOf((*MockRepository)(nil).CountExternalAccountsByUserID), ctx, userID)
}

// CreateExternalAccount mocks base method.
func (m *MockRepository) CreateExternalAccount(ctx context.Context, account *repository.ExternalAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExternalAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateExternalAccount indicates an expected call of CreateExternalAccount.
func (mr *MockRepositoryMockRecorder) CreateExternalAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExternalAccount", reflect.TypeOf((*MockRepository)(nil).CreateExternalAccount), ctx, account)
}

// CreateMagicCode mocks base method.
func (m *MockRepository) CreateMagicCode(ctx context.Context, code, email, phone string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMagicCode", ctx, code, email, phone, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMagicCode indicates an expected call of CreateMagicCode.
func (mr *MockRepositoryMockRecorder) CreateMagicCode(ctx, code, email, phone, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMagicCode", reflect.TypeOf((*MockRepository)(nil).CreateMagicCode), ctx, code, email, phone, expiresAt)
}

// CreateOAuthState mocks base method.
func (m *MockRepository) CreateOAuthState(ctx context.Context, state *repository.OAuthState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOAuthState indicates an expected call of CreateOAuthState.
func (mr *MockRepositoryMockRecorder) CreateOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthState", reflect.TypeOf((*MockRepository)(nil).CreateOAuthState), ctx, state)
}

// CreatePendingContactChange mocks base method.
func (m *MockRepository) CreatePendingContactChange(ctx context.Context, id, userID, changeType, newValue, code string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePendingContactChange", ctx, id, userID, changeType, newValue, code, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePendingContactChange indicates an expected call of CreatePendingContactChange.
func (mr *MockRepositoryMockRecorder) CreatePendingContactChange(ctx, id, userID, changeType, newValue, code, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePendingContactChange", reflect.TypeOf((*MockRepository)(nil).CreatePendingContactChange), ctx, id, userID, changeType, newValue, code, expiresAt)
}

// CreateSession mocks base method.
func (m *MockRepository) CreateSession(ctx context.Context, session *repository.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRepositoryMockRecorder) CreateSession(ctx, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRepository)(nil).CreateSession), ctx, session)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, id, email, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, id, email, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, id, email, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, id, email, phone)
}

// DeleteExternalAccount mocks base method.
func (m *MockRepository) DeleteExternalAccount(ctx context.Context, id, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalAccount", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalAccount indicates an expected call of DeleteExternalAccount.
func (mr *MockRepositoryMockRecorder) DeleteExternalAccount(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalAccount", reflect.TypeOf((*MockRepository)(nil).DeleteExternalAccount), ctx, id, userID)
}

// DeleteExternalAccountByProvider mocks base method.
func (m *MockRepository) DeleteExternalAccountByProvider(ctx context.Context, userID, provider string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExternalAccountByProvider", ctx, userID, provider)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExternalAccountByProvider indicates an expected call of DeleteExternalAccountByProvider.
func (mr *MockRepositoryMockRecorder) DeleteExternalAccountByProvider(ctx, userID, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExternalAccountByProvider", reflect.TypeOf((*MockRepository)(nil).DeleteExternalAccountByProvider), ctx, userID, provider)
}

// DeleteOAuthState mocks base method.
func (m *MockRepository) DeleteOAuthState(ctx context.Context, state string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOAuthState", ctx, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOAuthState indicates an expected call of DeleteOAuthState.
func (mr *MockRepositoryMockRecorder) DeleteOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOAuthState", reflect.TypeOf((*MockRepository)(nil).DeleteOAuthState), ctx, state)
}

// DeletePendingContactChange mocks base method.
func (m *MockRepository) DeletePendingContactChange(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePendingContactChange", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePendingContactChange indicates an expected call of DeletePendingContactChange.
func (mr *MockRepositoryMockRecorder) DeletePendingContactChange(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePendingContactChange", reflect.TypeOf((*MockRepository)(nil).DeletePendingContactChange), ctx, id)
}

// GetExternalAccountByProviderAndEmail mocks base method.
func (m *MockRepository) GetExternalAccountByProviderAndEmail(ctx context.Context, provider, email string) (*repository.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccountByProviderAndEmail", ctx, provider, email)
	ret0, _ := ret[0].(*repository.ExternalAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalAccountByProviderAndEmail indicates an expected call of GetExternalAccountByProviderAndEmail.
func (mr *MockRepositoryMockRecorder) GetExternalAccountByProviderAndEmail(ctx, provider, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccountByProviderAndEmail", reflect.TypeOf((*MockRepository)(nil).GetExternalAccountByProviderAndEmail), ctx, provider, email)
}

// GetExternalAccountByProviderUserID mocks base method.
func (m *MockRepository) GetExternalAccountByProviderUserID(ctx context.Context, provider, providerUserID string) (*repository.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccountByProviderUserID", ctx, provider, providerUserID)
	ret0, _ := ret[0].(*repository.ExternalAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalAccountByProviderUserID indicates an expected call of GetExternalAccountByProviderUserID.
func (mr *MockRepositoryMockRecorder) GetExternalAccountByProviderUserID(ctx, provider, providerUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccountByProviderUserID", reflect.TypeOf((*MockRepository)(nil).GetExternalAccountByProviderUserID), ctx, provider, providerUserID)
}

// GetExternalAccountsByUserID mocks base method.
func (m *MockRepository) GetExternalAccountsByUserID(ctx context.Context, userID string) ([]*repository.ExternalAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExternalAccountsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*repository.ExternalAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExternalAccountsByUserID indicates an expected call of GetExternalAccountsByUserID.
func (mr *MockRepositoryMockRecorder) GetExternalAccountsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExternalAccountsByUserID", reflect.TypeOf((*MockRepository)(nil).GetExternalAccountsByUserID), ctx, userID)
}

// GetOAuthState mocks base method.
func (m *MockRepository) GetOAuthState(ctx context.Context, state string) (*repository.OAuthState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOAuthState", ctx, state)
	ret0, _ := ret[0].(*repository.OAuthState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOAuthState indicates an expected call of GetOAuthState.
func (mr *MockRepositoryMockRecorder) GetOAuthState(ctx, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOAuthState", reflect.TypeOf((*MockRepository)(nil).GetOAuthState), ctx, state)
}

// GetPendingContactChange mocks base method.
func (m *MockRepository) GetPendingContactChange(ctx context.Context, userID, changeType, code string) (*repository.PendingContactChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingContactChange", ctx, userID, changeType, code)
	ret0, _ := ret[0].(*repository.PendingContactChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingContactChange indicates an expected call of GetPendingContactChange.
func (mr *MockRepositoryMockRecorder) GetPendingContactChange(ctx, userID, changeType, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingContactChange", reflect.TypeOf((*MockRepository)(nil).GetPendingContactChange), ctx, userID, changeType, code)
}

// GetSessionByID mocks base method.
func (m *MockRepository) GetSessionByID(ctx context.Context, id string) (*repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByID", ctx, id)
	ret0, _ := ret[0].(*repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByID indicates an expected call of GetSessionByID.
func (mr *MockRepositoryMockRecorder) GetSessionByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByID", reflect.TypeOf((*MockRepository)(nil).GetSessionByID), ctx, id)
}

// GetSessionByRefreshTokenHash mocks base method.
func (m *MockRepository) GetSessionByRefreshTokenHash(ctx context.Context, hash string) (*repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionByRefreshTokenHash", ctx, hash)
	ret0, _ := ret[0].(*repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionByRefreshTokenHash indicates an expected call of GetSessionByRefreshTokenHash.
func (mr *MockRepositoryMockRecorder) GetSessionByRefreshTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionByRefreshTokenHash", reflect.TypeOf((*MockRepository)(nil).GetSessionByRefreshTokenHash), ctx, hash)
}

// GetSessionsByUserID mocks base method.
func (m *MockRepository) GetSessionsByUserID(ctx context.Context, userID string) ([]*repository.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSessionsByUserID", ctx, userID)
	ret0, _ := ret[0].([]*repository.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSessionsByUserID indicates an expected call of GetSessionsByUserID.
func (mr *MockRepositoryMockRecorder) GetSessionsByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSessionsByUserID", reflect.TypeOf((*MockRepository)(nil).GetSessionsByUserID), ctx, userID)
}

// GetUserByEmail mocks base method.
func (m *MockRepository) GetUserByEmail(ctx context.Context, email string) (*store.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*store.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockRepositoryMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockRepository)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockRepository) GetUserByID(ctx context.Context, id string) (*store.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*store.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockRepositoryMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockRepository)(nil).GetUserByID), ctx, id)
}

// GetUserByPhone mocks base method.
func (m *MockRepository) GetUserByPhone(ctx context.Context, phone string) (*store.AuthUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByPhone", ctx, phone)
	ret0, _ := ret[0].(*store.AuthUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByPhone indicates an expected call of GetUserByPhone.
func (mr *MockRepositoryMockRecorder) GetUserByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByPhone", reflect.TypeOf((*MockRepository)(nil).GetUserByPhone), ctx, phone)
}

// GetValidMagicCodeByEmail mocks base method.
func (m *MockRepository) GetValidMagicCodeByEmail(ctx context.Context, email, code string) (*store.AuthMagicCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidMagicCodeByEmail", ctx, email, code)
	ret0, _ := ret[0].(*store.AuthMagicCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidMagicCodeByEmail indicates an expected call of GetValidMagicCodeByEmail.
func (mr *MockRepositoryMockRecorder) GetValidMagicCodeByEmail(ctx, email, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidMagicCodeByEmail", reflect.TypeOf((*MockRepository)(nil).GetValidMagicCodeByEmail), ctx, email, code)
}

// GetValidMagicCodeByPhone mocks base method.
func (m *MockRepository) GetValidMagicCodeByPhone(ctx context.Context, phone, code string) (*store.AuthMagicCode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidMagicCodeByPhone", ctx, phone, code)
	ret0, _ := ret[0].(*store.AuthMagicCode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidMagicCodeByPhone indicates an expected call of GetValidMagicCodeByPhone.
func (mr *MockRepositoryMockRecorder) GetValidMagicCodeByPhone(ctx, phone, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidMagicCodeByPhone", reflect.TypeOf((*MockRepository)(nil).GetValidMagicCodeByPhone), ctx, phone, code)
}

// InvalidateMagicCodes mocks base method.
func (m *MockRepository) InvalidateMagicCodes(ctx context.Context, email, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateMagicCodes", ctx, email, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateMagicCodes indicates an expected call of InvalidateMagicCodes.
func (mr *MockRepositoryMockRecorder) InvalidateMagicCodes(ctx, email, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateMagicCodes", reflect.TypeOf((*MockRepository)(nil).InvalidateMagicCodes), ctx, email, phone)
}

// IsTokenBlacklisted mocks base method.
func (m *MockRepository) IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTokenBlacklisted", ctx, tokenHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTokenBlacklisted indicates an expected call of IsTokenBlacklisted.
func (mr *MockRepositoryMockRecorder) IsTokenBlacklisted(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTokenBlacklisted", reflect.TypeOf((*MockRepository)(nil).IsTokenBlacklisted), ctx, tokenHash)
}

// RevokeAllUserSessions mocks base method.
func (m *MockRepository) RevokeAllUserSessions(ctx context.Context, userID, exceptSessionID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllUserSessions", ctx, userID, exceptSessionID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeAllUserSessions indicates an expected call of RevokeAllUserSessions.
func (mr *MockRepositoryMockRecorder) RevokeAllUserSessions(ctx, userID, exceptSessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllUserSessions", reflect.TypeOf((*MockRepository)(nil).RevokeAllUserSessions), ctx, userID, exceptSessionID)
}

// RevokeSession mocks base method.
func (m *MockRepository) RevokeSession(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockRepositoryMockRecorder) RevokeSession(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockRepository)(nil).RevokeSession), ctx, id)
}

// UpdateExternalAccountProfile mocks base method.
func (m *MockRepository) UpdateExternalAccountProfile(ctx context.Context, provider, providerUserID, name, avatarURL, email string, rawData map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExternalAccountProfile", ctx, provider, providerUserID, name, avatarURL, email, rawData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExternalAccountProfile indicates an expected call of UpdateExternalAccountProfile.
func (mr *MockRepositoryMockRecorder) UpdateExternalAccountProfile(ctx, provider, providerUserID, name, avatarURL, email, rawData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExternalAccountProfile", reflect.TypeOf((*MockRepository)(nil).UpdateExternalAccountProfile), ctx, provider, providerUserID, name, avatarURL, email, rawData)
}

// UpdateExternalAccountTokens mocks base method.
func (m *MockRepository) UpdateExternalAccountTokens(ctx context.Context, provider, providerUserID, accessToken, refreshToken string, expiresAt *time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExternalAccountTokens", ctx, provider, providerUserID, accessToken, refreshToken, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExternalAccountTokens indicates an expected call of UpdateExternalAccountTokens.
func (mr *MockRepositoryMockRecorder) UpdateExternalAccountTokens(ctx, provider, providerUserID, accessToken, refreshToken, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExternalAccountTokens", reflect.TypeOf((*MockRepository)(nil).UpdateExternalAccountTokens), ctx, provider, providerUserID, accessToken, refreshToken, expiresAt)
}

// UpdateSessionActivity mocks base method.
func (m *MockRepository) UpdateSessionActivity(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSessionActivity", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSessionActivity indicates an expected call of UpdateSessionActivity.
func (mr *MockRepositoryMockRecorder) UpdateSessionActivity(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSessionActivity", reflect.TypeOf((*MockRepository)(nil).UpdateSessionActivity), ctx, id)
}

// UpdateUserProfile mocks base method.
func (m *MockRepository) UpdateUserProfile(ctx context.Context, id, displayName, avatarURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserProfile", ctx, id, displayName, avatarURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserProfile indicates an expected call of UpdateUserProfile.
func (mr *MockRepositoryMockRecorder) UpdateUserProfile(ctx, id, displayName, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserProfile", reflect.TypeOf((*MockRepository)(nil).UpdateUserProfile), ctx, id, displayName, avatarURL)
}

// WithTx mocks base method.
func (m *MockRepository) WithTx(ctx context.Context, fn func(repository.Repository) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockRepositoryMockRecorder) WithTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockRepository)(nil).WithTx), ctx, fn)
}
