// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignUserRole = `-- name: AssignUserRole :exec
INSERT INTO auth.user_roles (user_id, role_id, created_at, updated_at)
VALUES ($1, (SELECT id FROM auth.roles WHERE LOWER(name) = LOWER($2) AND deleted_at IS NULL), NOW(), NOW())
ON CONFLICT (user_id, role_id) DO UPDATE SET updated_at = NOW()
`

type AssignUserRoleParams struct {
	UserID   string `json:"user_id"`
	RoleName string `json:"role_name"`
}

func (q *Queries) AssignUserRole(ctx context.Context, arg AssignUserRoleParams) error {
	_, err := q.db.Exec(ctx, assignUserRole, arg.UserID, arg.RoleName)
	return err
}

const blacklistToken = `-- name: BlacklistToken :exec

INSERT INTO auth.token_blacklist (token_hash, user_id, expires_at, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (token_hash) DO NOTHING
`

type BlacklistTokenParams struct {
	TokenHash string             `json:"token_hash"`
	UserID    string             `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Reason    pgtype.Text        `json:"reason"`
}

// ========================
// Token Blacklist
// ========================
func (q *Queries) BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error {
	_, err := q.db.Exec(ctx, blacklistToken,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Reason,
	)
	return err
}

const cleanupExpiredBlacklistEntries = `-- name: CleanupExpiredBlacklistEntries :exec
DELETE FROM auth.token_blacklist WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredBlacklistEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredBlacklistEntries)
	return err
}

const cleanupExpiredMagicCodes = `-- name: CleanupExpiredMagicCodes :exec
DELETE FROM auth.magic_codes WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredMagicCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredMagicCodes)
	return err
}

const cleanupExpiredOAuthStates = `-- name: CleanupExpiredOAuthStates :exec
DELETE FROM auth.oauth_states WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) CleanupExpiredOAuthStates(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredOAuthStates)
	return err
}

const cleanupExpiredSessions = `-- name: CleanupExpiredSessions :exec
DELETE FROM auth.sessions WHERE expires_at < CURRENT_TIMESTAMP - INTERVAL '7 days'
`

func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredSessions)
	return err
}

const countExternalAccountsByUserID = `-- name: CountExternalAccountsByUserID :one
SELECT COUNT(*) FROM auth.user_external_accounts WHERE user_id = $1
`

func (q *Queries) CountExternalAccountsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countExternalAccountsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExternalAccount = `-- name: CreateExternalAccount :exec

INSERT INTO auth.user_external_accounts (id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, token_expires_at, raw_data)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateExternalAccountParams struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	Email          pgtype.Text        `json:"email"`
	Name           pgtype.Text        `json:"name"`
	AvatarUrl      pgtype.Text        `json:"avatar_url"`
	AccessToken    pgtype.Text        `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	RawData        []byte             `json:"raw_data"`
}

// ========================
// External OAuth Accounts
// ========================
func (q *Queries) CreateExternalAccount(ctx context.Context, arg CreateExternalAccountParams) error {
	_, err := q.db.Exec(ctx, createExternalAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.AvatarUrl,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.RawData,
	)
	return err
}

const createMagicCode = `-- name: CreateMagicCode :exec

INSERT INTO auth.magic_codes (code, user_email, user_phone, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateMagicCodeParams struct {
	Code      string             `json:"code"`
	UserEmail pgtype.Text        `json:"user_email"`
	UserPhone pgtype.Text        `json:"user_phone"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ========================
// Magic Codes (Passwordless)
// ========================
func (q *Queries) CreateMagicCode(ctx context.Context, arg CreateMagicCodeParams) error {
	_, err := q.db.Exec(ctx, createMagicCode,
		arg.Code,
		arg.UserEmail,
		arg.UserPhone,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthState = `-- name: CreateOAuthState :exec

INSERT INTO auth.oauth_states (state, provider, redirect_url, user_id, action, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateOAuthStateParams struct {
	State       string             `json:"state"`
	Provider    string             `json:"provider"`
	RedirectUrl pgtype.Text        `json:"redirect_url"`
	UserID      pgtype.Text        `json:"user_id"`
	Action      string             `json:"action"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// ========================
// OAuth State Tokens
// ========================
func (q *Queries) CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error {
	_, err := q.db.Exec(ctx, createOAuthState,
		arg.State,
		arg.Provider,
		arg.RedirectUrl,
		arg.UserID,
		arg.Action,
		arg.ExpiresAt,
	)
	return err
}

const createPendingContactChange = `-- name: CreatePendingContactChange :exec

INSERT INTO auth.pending_contact_changes (id, user_id, change_type, new_value, verification_code, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreatePendingContactChangeParams struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	ChangeType       string             `json:"change_type"`
	NewValue         string             `json:"new_value"`
	VerificationCode string             `json:"verification_code"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// ========================
// Pending Contact Changes
// ========================
func (q *Queries) CreatePendingContactChange(ctx context.Context, arg CreatePendingContactChangeParams) error {
	_, err := q.db.Exec(ctx, createPendingContactChange,
		arg.ID,
		arg.UserID,
		arg.ChangeType,
		arg.NewValue,
		arg.VerificationCode,
		arg.ExpiresAt,
	)
	return err
}

const createSession = `-- name: CreateSession :exec

INSERT INTO auth.sessions (id, user_id, refresh_token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSessionParams struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

// ========================
// Sessions
// ========================
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO auth.users (id, email, phone) VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID    string      `json:"id"`
	Email pgtype.Text `json:"email"`
	Phone pgtype.Text `json:"phone"`
}

// ========================
// User Management
// ========================
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Email, arg.Phone)
	return err
}

const deleteExpiredPendingContactChanges = `-- name: DeleteExpiredPendingContactChanges :exec
DELETE FROM auth.pending_contact_changes WHERE expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredPendingContactChanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingContactChanges)
	return err
}

const deleteExternalAccount = `-- name: DeleteExternalAccount :exec
DELETE FROM auth.user_external_accounts WHERE id = $1 AND user_id = $2
`

type DeleteExternalAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteExternalAccount(ctx context.Context, arg DeleteExternalAccountParams) error {
	_, err := q.db.Exec(ctx, deleteExternalAccount, arg.ID, arg.UserID)
	return err
}

const deleteExternalAccountByProvider = `-- name: DeleteExternalAccountByProvider :exec
DELETE FROM auth.user_external_accounts WHERE user_id = $1 AND provider = $2
`

type DeleteExternalAccountByProviderParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteExternalAccountByProvider(ctx context.Context, arg DeleteExternalAccountByProviderParams) error {
	_, err := q.db.Exec(ctx, deleteExternalAccountByProvider, arg.UserID, arg.Provider)
	return err
}

const deleteMagicCodesByEmail = `-- name: DeleteMagicCodesByEmail :exec
DELETE FROM auth.magic_codes WHERE user_email = $1
`

func (q *Queries) DeleteMagicCodesByEmail(ctx context.Context, userEmail pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteMagicCodesByEmail, userEmail)
	return err
}

const deleteMagicCodesByPhone = `-- name: DeleteMagicCodesByPhone :exec
DELETE FROM auth.magic_codes WHERE user_phone = $1
`

func (q *Queries) DeleteMagicCodesByPhone(ctx context.Context, userPhone pgtype.Text) error {
	_, err := q.db.Exec(ctx, deleteMagicCodesByPhone, userPhone)
	return err
}

const deleteOAuthState = `-- name: DeleteOAuthState :exec
DELETE FROM auth.oauth_states WHERE state = $1
`

func (q *Queries) DeleteOAuthState(ctx context.Context, state string) error {
	_, err := q.db.Exec(ctx, deleteOAuthState, state)
	return err
}

const deletePendingContactChange = `-- name: DeletePendingContactChange :exec
DELETE FROM auth.pending_contact_changes WHERE id = $1
`

func (q *Queries) DeletePendingContactChange(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePendingContactChange, id)
	return err
}

const getExternalAccountByProviderAndEmail = `-- name: GetExternalAccountByProviderAndEmail :one
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, token_expires_at, raw_data, created_at, updated_at FROM auth.user_external_accounts WHERE provider = $1 AND email = $2 LIMIT 1
`

type GetExternalAccountByProviderAndEmailParams struct {
	Provider string      `json:"provider"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) GetExternalAccountByProviderAndEmail(ctx context.Context, arg GetExternalAccountByProviderAndEmailParams) (AuthUserExternalAccount, error) {
	row := q.db.QueryRow(ctx, getExternalAccountByProviderAndEmail, arg.Provider, arg.Email)
	var i AuthUserExternalAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalAccountByProviderAndUserID = `-- name: GetExternalAccountByProviderAndUserID :one
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, token_expires_at, raw_data, created_at, updated_at FROM auth.user_external_accounts WHERE provider = $1 AND provider_user_id = $2 LIMIT 1
`

type GetExternalAccountByProviderAndUserIDParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetExternalAccountByProviderAndUserID(ctx context.Context, arg GetExternalAccountByProviderAndUserIDParams) (AuthUserExternalAccount, error) {
	row := q.db.QueryRow(ctx, getExternalAccountByProviderAndUserID, arg.Provider, arg.ProviderUserID)
	var i AuthUserExternalAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExternalAccountsByUserID = `-- name: GetExternalAccountsByUserID :many
SELECT id, user_id, provider, provider_user_id, email, name, avatar_url, access_token, refresh_token, token_expires_at, raw_data, created_at, updated_at FROM auth.user_external_accounts WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetExternalAccountsByUserID(ctx context.Context, userID string) ([]AuthUserExternalAccount, error) {
	rows, err := q.db.Query(ctx, getExternalAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUserExternalAccount
	for rows.Next() {
		var i AuthUserExternalAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.Name,
			&i.AvatarUrl,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOAuthState = `-- name: GetOAuthState :one
SELECT state, provider, redirect_url, user_id, action, created_at, updated_at, expires_at FROM auth.oauth_states WHERE state = $1 AND expires_at > CURRENT_TIMESTAMP LIMIT 1
`

func (q *Queries) GetOAuthState(ctx context.Context, state string) (AuthOauthState, error) {
	row := q.db.QueryRow(ctx, getOAuthState, state)
	var i AuthOauthState
	err := row.Scan(
		&i.State,
		&i.Provider,
		&i.RedirectUrl,
		&i.UserID,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getPendingContactChange = `-- name: GetPendingContactChange :one
SELECT id, user_id, change_type, new_value, verification_code, created_at, updated_at, expires_at FROM auth.pending_contact_changes
WHERE user_id = $1 AND change_type = $2 AND verification_code = $3 AND expires_at > CURRENT_TIMESTAMP
LIMIT 1
`

type GetPendingContactChangeParams struct {
	UserID           string `json:"user_id"`
	ChangeType       string `json:"change_type"`
	VerificationCode string `json:"verification_code"`
}

func (q *Queries) GetPendingContactChange(ctx context.Context, arg GetPendingContactChangeParams) (AuthPendingContactChange, error) {
	row := q.db.QueryRow(ctx, getPendingContactChange, arg.UserID, arg.ChangeType, arg.VerificationCode)
	var i AuthPendingContactChange
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChangeType,
		&i.NewValue,
		&i.VerificationCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, updated_at, last_active_at, expires_at, revoked_at FROM auth.sessions WHERE id = $1 AND revoked_at IS NULL LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, updated_at, last_active_at, expires_at, revoked_at FROM auth.sessions WHERE refresh_token_hash = $1 AND revoked_at IS NULL AND expires_at > CURRENT_TIMESTAMP LIMIT 1
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionsByUserID = `-- name: GetSessionsByUserID :many
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, updated_at, last_active_at, expires_at, revoked_at FROM auth.sessions WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > CURRENT_TIMESTAMP ORDER BY last_active_at DESC
`

func (q *Queries) GetSessionsByUserID(ctx context.Context, userID string) ([]AuthSession, error) {
	rows, err := q.db.Query(ctx, getSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthSession
	for rows.Next() {
		var i AuthSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnpublishedOutbox = `-- name: GetUnpublishedOutbox :many
SELECT id, event_name, payload, created_at, updated_at, published_at FROM auth.outbox
WHERE published_at IS NULL
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetUnpublishedOutbox(ctx context.Context, limit int32) ([]AuthOutbox, error) {
	rows, err := q.db.Query(ctx, getUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthOutbox
	for rows.Next() {
		var i AuthOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventName,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, display_name, avatar_url, status, email_verified, phone_verified, timezone, created_at, updated_at FROM auth.users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, phone, display_name, avatar_url, status, email_verified, phone_verified, timezone, created_at, updated_at FROM auth.users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, display_name, avatar_url, status, email_verified, phone_verified, timezone, created_at, updated_at FROM auth.users WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone pgtype.Text) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.EmailVerified,
		&i.PhoneVerified,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRole = `-- name: GetUserRole :one
SELECT r.name
FROM auth.roles r
JOIN auth.user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
  AND r.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserRole(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserRole, userID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getValidMagicCodeByEmail = `-- name: GetValidMagicCodeByEmail :one
SELECT code, user_email, user_phone, expires_at, created_at, updated_at FROM auth.magic_codes
WHERE user_email = $1 AND code = $2 AND expires_at > $3
ORDER BY created_at DESC LIMIT 1
`

type GetValidMagicCodeByEmailParams struct {
	UserEmail pgtype.Text        `json:"user_email"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetValidMagicCodeByEmail(ctx context.Context, arg GetValidMagicCodeByEmailParams) (AuthMagicCode, error) {
	row := q.db.QueryRow(ctx, getValidMagicCodeByEmail, arg.UserEmail, arg.Code, arg.ExpiresAt)
	var i AuthMagicCode
	err := row.Scan(
		&i.Code,
		&i.UserEmail,
		&i.UserPhone,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidMagicCodeByPhone = `-- name: GetValidMagicCodeByPhone :one
SELECT code, user_email, user_phone, expires_at, created_at, updated_at FROM auth.magic_codes
WHERE user_phone = $1 AND code = $2 AND expires_at > $3
ORDER BY created_at DESC LIMIT 1
`

type GetValidMagicCodeByPhoneParams struct {
	UserPhone pgtype.Text        `json:"user_phone"`
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetValidMagicCodeByPhone(ctx context.Context, arg GetValidMagicCodeByPhoneParams) (AuthMagicCode, error) {
	row := q.db.QueryRow(ctx, getValidMagicCodeByPhone, arg.UserPhone, arg.Code, arg.ExpiresAt)
	var i AuthMagicCode
	err := row.Scan(
		&i.Code,
		&i.UserEmail,
		&i.UserPhone,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isTokenBlacklisted = `-- name: IsTokenBlacklisted :one
SELECT EXISTS(SELECT 1 FROM auth.token_blacklist WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenBlacklisted, tokenHash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE auth.users SET email_verified = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const markOutboxAsPublished = `-- name: MarkOutboxAsPublished :exec
UPDATE auth.outbox
SET published_at = NOW()
WHERE id = ANY($1::varchar[])
`

func (q *Queries) MarkOutboxAsPublished(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, markOutboxAsPublished, dollar_1)
	return err
}

const markPhoneVerified = `-- name: MarkPhoneVerified :exec
UPDATE auth.users SET phone_verified = TRUE, updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkPhoneVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markPhoneVerified, id)
	return err
}

const removeUserRoles = `-- name: RemoveUserRoles :exec
DELETE FROM auth.user_roles WHERE user_id = $1
`

func (q *Queries) RemoveUserRoles(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, removeUserRoles, userID)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :execrows
UPDATE auth.sessions SET revoked_at = CURRENT_TIMESTAMP WHERE user_id = $1 AND revoked_at IS NULL AND ($2 = '' OR id != $2)
`

type RevokeAllUserSessionsParams struct {
	UserID  string      `json:"user_id"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserSessions, arg.UserID, arg.Column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE auth.sessions SET revoked_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const storeOutbox = `-- name: StoreOutbox :exec

INSERT INTO auth.outbox (id, event_name, payload, created_at)
VALUES ($1, $2, $3, NOW())
`

type StoreOutboxParams struct {
	ID        string `json:"id"`
	EventName string `json:"event_name"`
	Payload   []byte `json:"payload"`
}

// ========================
// Outbox
// ========================
func (q *Queries) StoreOutbox(ctx context.Context, arg StoreOutboxParams) error {
	_, err := q.db.Exec(ctx, storeOutbox, arg.ID, arg.EventName, arg.Payload)
	return err
}

const updateExternalAccountProfile = `-- name: UpdateExternalAccountProfile :exec
UPDATE auth.user_external_accounts
SET name = $3, avatar_url = $4, email = $5, raw_data = $6, updated_at = CURRENT_TIMESTAMP
WHERE provider = $1 AND provider_user_id = $2
`

type UpdateExternalAccountProfileParams struct {
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Name           pgtype.Text `json:"name"`
	AvatarUrl      pgtype.Text `json:"avatar_url"`
	Email          pgtype.Text `json:"email"`
	RawData        []byte      `json:"raw_data"`
}

func (q *Queries) UpdateExternalAccountProfile(ctx context.Context, arg UpdateExternalAccountProfileParams) error {
	_, err := q.db.Exec(ctx, updateExternalAccountProfile,
		arg.Provider,
		arg.ProviderUserID,
		arg.Name,
		arg.AvatarUrl,
		arg.Email,
		arg.RawData,
	)
	return err
}

const updateExternalAccountTokens = `-- name: UpdateExternalAccountTokens :exec
UPDATE auth.user_external_accounts
SET access_token = $3, refresh_token = $4, token_expires_at = $5, updated_at = CURRENT_TIMESTAMP
WHERE provider = $1 AND provider_user_id = $2
`

type UpdateExternalAccountTokensParams struct {
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	AccessToken    pgtype.Text        `json:"access_token"`
	RefreshToken   pgtype.Text        `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateExternalAccountTokens(ctx context.Context, arg UpdateExternalAccountTokensParams) error {
	_, err := q.db.Exec(ctx, updateExternalAccountTokens,
		arg.Provider,
		arg.ProviderUserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE auth.sessions SET last_active_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, id)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
UPDATE auth.users SET display_name = $2, avatar_url = $3, timezone = $4, updated_at = CURRENT_TIMESTAMP WHERE id = $1
`

type UpdateUserProfileParams struct {
	ID          string      `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Timezone    pgtype.Text `json:"timezone"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.ID,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Timezone,
	)
	return err
}
