// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createMagicCode = `-- name: CreateMagicCode :exec
INSERT INTO magic_codes (code, user_email, user_phone, expires_at) VALUES ($1, $2, $3, $4)
`

type CreateMagicCodeParams struct {
	Code      string         `json:"code"`
	UserEmail sql.NullString `json:"user_email"`
	UserPhone sql.NullString `json:"user_phone"`
	ExpiresAt time.Time      `json:"expires_at"`
}

func (q *Queries) CreateMagicCode(ctx context.Context, arg CreateMagicCodeParams) error {
	_, err := q.db.ExecContext(ctx, createMagicCode,
		arg.Code,
		arg.UserEmail,
		arg.UserPhone,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, email, phone) VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID    string         `json:"id"`
	Email sql.NullString `json:"email"`
	Phone sql.NullString `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser, arg.ID, arg.Email, arg.Phone)
	return err
}

const deleteMagicCodesByEmail = `-- name: DeleteMagicCodesByEmail :exec
DELETE FROM magic_codes WHERE user_email = $1
`

func (q *Queries) DeleteMagicCodesByEmail(ctx context.Context, userEmail sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMagicCodesByEmail, userEmail)
	return err
}

const deleteMagicCodesByPhone = `-- name: DeleteMagicCodesByPhone :exec
DELETE FROM magic_codes WHERE user_phone = $1
`

func (q *Queries) DeleteMagicCodesByPhone(ctx context.Context, userPhone sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteMagicCodesByPhone, userPhone)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, phone, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, email, phone, created_at, updated_at FROM users WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone sql.NullString) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getValidMagicCodeByEmail = `-- name: GetValidMagicCodeByEmail :one
SELECT code, user_email, user_phone, expires_at, created_at FROM magic_codes
WHERE user_email = $1 AND code = $2 AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC LIMIT 1
`

type GetValidMagicCodeByEmailParams struct {
	UserEmail sql.NullString `json:"user_email"`
	Code      string         `json:"code"`
}

func (q *Queries) GetValidMagicCodeByEmail(ctx context.Context, arg GetValidMagicCodeByEmailParams) (MagicCode, error) {
	row := q.db.QueryRowContext(ctx, getValidMagicCodeByEmail, arg.UserEmail, arg.Code)
	var i MagicCode
	err := row.Scan(
		&i.Code,
		&i.UserEmail,
		&i.UserPhone,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidMagicCodeByPhone = `-- name: GetValidMagicCodeByPhone :one
SELECT code, user_email, user_phone, expires_at, created_at FROM magic_codes
WHERE user_phone = $1 AND code = $2 AND expires_at > CURRENT_TIMESTAMP
ORDER BY created_at DESC LIMIT 1
`

type GetValidMagicCodeByPhoneParams struct {
	UserPhone sql.NullString `json:"user_phone"`
	Code      string         `json:"code"`
}

func (q *Queries) GetValidMagicCodeByPhone(ctx context.Context, arg GetValidMagicCodeByPhoneParams) (MagicCode, error) {
	row := q.db.QueryRowContext(ctx, getValidMagicCodeByPhone, arg.UserPhone, arg.Code)
	var i MagicCode
	err := row.Scan(
		&i.Code,
		&i.UserEmail,
		&i.UserPhone,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
