// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
	"database/sql"
)

type Querier interface {
	// ========================
	// Token Blacklist
	// ========================
	BlacklistToken(ctx context.Context, arg BlacklistTokenParams) error
	CleanupExpiredBlacklistEntries(ctx context.Context) error
	CleanupExpiredMagicCodes(ctx context.Context) error
	CleanupExpiredOAuthStates(ctx context.Context) error
	CleanupExpiredSessions(ctx context.Context) error
	CountExternalAccountsByUserID(ctx context.Context, userID string) (int64, error)
	// ========================
	// External OAuth Accounts
	// ========================
	CreateExternalAccount(ctx context.Context, arg CreateExternalAccountParams) error
	// ========================
	// Magic Codes (Passwordless)
	// ========================
	CreateMagicCode(ctx context.Context, arg CreateMagicCodeParams) error
	// ========================
	// OAuth State Tokens
	// ========================
	CreateOAuthState(ctx context.Context, arg CreateOAuthStateParams) error
	// ========================
	// Pending Contact Changes
	// ========================
	CreatePendingContactChange(ctx context.Context, arg CreatePendingContactChangeParams) error
	// ========================
	// Sessions
	// ========================
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// ========================
	// User Management
	// ========================
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteExpiredPendingContactChanges(ctx context.Context) error
	DeleteExternalAccount(ctx context.Context, arg DeleteExternalAccountParams) error
	DeleteExternalAccountByProvider(ctx context.Context, arg DeleteExternalAccountByProviderParams) error
	DeleteMagicCodesByEmail(ctx context.Context, userEmail sql.NullString) error
	DeleteMagicCodesByPhone(ctx context.Context, userPhone sql.NullString) error
	DeleteOAuthState(ctx context.Context, state string) error
	DeletePendingContactChange(ctx context.Context, id string) error
	GetExternalAccountByProviderAndEmail(ctx context.Context, arg GetExternalAccountByProviderAndEmailParams) (AuthUserExternalAccount, error)
	GetExternalAccountByProviderAndUserID(ctx context.Context, arg GetExternalAccountByProviderAndUserIDParams) (AuthUserExternalAccount, error)
	GetExternalAccountsByUserID(ctx context.Context, userID string) ([]AuthUserExternalAccount, error)
	GetOAuthState(ctx context.Context, state string) (AuthOauthState, error)
	GetPendingContactChange(ctx context.Context, arg GetPendingContactChangeParams) (AuthPendingContactChange, error)
	GetSessionByID(ctx context.Context, id string) (AuthSession, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (AuthSession, error)
	GetSessionsByUserID(ctx context.Context, userID string) ([]AuthSession, error)
	GetUserByEmail(ctx context.Context, email sql.NullString) (AuthUser, error)
	GetUserByID(ctx context.Context, id string) (AuthUser, error)
	GetUserByPhone(ctx context.Context, phone sql.NullString) (AuthUser, error)
	GetValidMagicCodeByEmail(ctx context.Context, arg GetValidMagicCodeByEmailParams) (AuthMagicCode, error)
	GetValidMagicCodeByPhone(ctx context.Context, arg GetValidMagicCodeByPhoneParams) (AuthMagicCode, error)
	IsTokenBlacklisted(ctx context.Context, tokenHash string) (bool, error)
	RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) (int64, error)
	RevokeSession(ctx context.Context, id string) error
	UpdateExternalAccountProfile(ctx context.Context, arg UpdateExternalAccountProfileParams) error
	UpdateExternalAccountTokens(ctx context.Context, arg UpdateExternalAccountTokensParams) error
	UpdateSessionActivity(ctx context.Context, id string) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
