apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "modulith.fullname" . }}
  labels:
    {{- include "modulith.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "modulith.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "modulith.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          {{- if eq .Values.deploymentType "module" }}
          image: "{{ .Values.image.repository }}-{{ .Values.moduleName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.image.repository }}-server:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.httpPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: {{ .Values.healthChecks.startup.path }}
              port: http
            failureThreshold: {{ .Values.healthChecks.startup.failureThreshold }}
            periodSeconds: {{ .Values.healthChecks.startup.periodSeconds }}
            initialDelaySeconds: {{ .Values.healthChecks.startup.initialDelaySeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthChecks.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthChecks.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.liveness.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthChecks.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthChecks.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthChecks.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.healthChecks.readiness.timeoutSeconds }}
          env:
            - name: ENV
              value: {{ .Values.config.env }}
            - name: DB_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ include "modulith.fullname" . }}-secrets
                  key: db-dsn
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "modulith.fullname" . }}-secrets
                  key: jwt-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
