apiVersion: v1
kind: Secret
metadata:
  name: {{ include "modulith.fullname" . }}-secrets
  labels:
    {{- include "modulith.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-dsn: {{ .Values.config.dbDsn | quote }}
  jwt-secret: {{ .Values.config.jwtSecret | quote }}
